language: python
python:
  - "2.7"
  - "3.6"

# command to install dependencies
install: "pip install -r requirements.txt"

# command to run tests
script: nosetests

deploy:
    # test pypi
  - provider: pypi
    user: "yergidy"
    password:
      secure: i94IneuP11Zpvv2PW5GwosK0WtsLa7iIg+c1sozDvESBXVi+929FCR/8e2wA9UNRMR+x6pzLO0x+15FXGFzoQ9pByP5tzhM08txL5XzUOpaG1WvPwbIyi8O4pKomjplhh2U0POybJUJooJbSiNNTtvFa0u+r24k1wsXDBX0TTAmXAoEd4h55XFMgzkkTXt1yS/Qt4tVRhcNSoy4puqpRwcy4sAK+HAfSoOSCMB2aO/jaJYehQ/K3FITjoF427eudCUcLuwpVo+91HD8ig4vjJkjNFbHJkovFzhDuEAYlZyI6PLppKvdKStJ29pnsv1d7K5h/+i0oAELb42OrUZa+sFicEZABDs5q47L28cdfce93J9r354a1/yjOnoLBtLdxRwSePWLCT5RbHfyQx5dolZsOefhp8H7PWCq8OWV+jUbYHFtjrnSARWWLszFOuhLWAI/gmaNCAHnNP6ZxgpnuuOiA9B0CJtoCLIzVruE02mUTWvFsAqWdCxmra8pDFJhFfal8RkDhDwMyu/hRR3oQvwv9GndAd4BOATSC+lIfH/CmmayjjvVrkEd7pTgMOmlm6m+yEk9PulNNGPCjSARkGbAbDWd1jXXEe62CC9xCf2DvDfV3qHZ3ZCAWpyuqvCMtmB5vbkIev8BJU6teqfcBsjfwgHvuGuhYflKYp4iQw3U=
    on:
      branch: master
      tags: true
      condition: $TRAVIS_PYTHON_VERSION = "2.7"
