language: python
python:
  - "2.7"
  - "3.6"

# command to install dependencies
install: "pip install -r requirements.txt"

# command to run tests
script: nosetests

deploy:
    # test pypi
  - provider: pypi
    user: "yergidy"
    password:
      secure: "xJ7w4zeS2YMrirhTH8PzEc0vRfXHZV6sp26DUNTczJggX+cx79lfui1sG4kQaMJ4GEzhBigBwh8kEkPEcJbwl/1u/tpv1Uoyn1Gmn/rln/0sUm3wPhG4o0w2U6WQKBgs8zdfgNIpIxAjNRQ0Eag80wr1hgWL7cICA7n914oJG1272q6/W+4qiRMDqxskqLUqQaqEdUsfmrGZJeOVu7zd+RJjLdu2A/mVcLtMMGeSjvyJam8ftQGZTtthKeaSqGMWexhFxZiXAJu2NHmTgeoqouzyom5EDcisw/Mng2bHosUgH1zXLgWmP/lRylJNMX874K+H78tTrW28Z01rwGudPxjBKyBxlx2rVlTuxzG6irtdf4h8kZdpSOPpviSpPkNdcRV6EzLGKEoqsSFoZxN4vLjXFp+hq4IWevpRcYdVYMpbx8FZTpRMPQmtYYl69a1QIy+f7KV3OTfQ3ZY5XvtJFDYusyP4Qyd4X0tO2+tiq8a2ZzmQzG6OrJxvFZdX/tx18HnFW+dhCFgHleR2UyiOKM426Xhpzjh4q7Z76yBCElshuBcwLRLyqyY9qSt1sGhWMwhHbnlLUN83U+qzjCS6j6e03KWI0p+GkZ1NTWv7xh68uyoH0iR4Qf17A+pV8KWVlDdq7pBz22l2ec9yXsptst5vhyuekAo7dWda8sd03II="
    on:
      branch: master
      tags: true
      condition: $TRAVIS_PYTHON_VERSION = "2.7"
