language: python
python:
  - "2.7"

# command to install dependencies
install: "pip install -r requirements.txt"

# command to run tests
script: nosetests

deploy:
    # test pypi
  - provider: pypi
    server: https://pypi.python.org/pypi
    user: "example"
    password:
      secure: "examplepassword"
    on:
      branch: master
      tags: true
      condition: $TRAVIS_PYTHON_VERSION = "2.7"
