kind: pipeline
name: build_n_test

steps:
- name: RIS-library-pytester-2.7
  image: python:2.7
  pull: true
  volumes:
  - name: drone_store
    path: /tmp/store
  environment:
    HTTP_PROXY: http://web-proxy.houston.hpecorp.net:8080
    PYTHON: 2
    GITHUB_USERNAME:
      from_secret: github_username
    GITHUB_PASSWORD:
      from_secret: github_password
    RESTLAX_FILE_PATH: /tmp/store/Restlax_web.txt
    DRONE_STORE_PATH: /tmp/store/
    PYTYPE_CONFIG: tests/pytype/pytype.cfg
    REPO_OWNER: intelligent-provisioning
    REPO_NAME: python-redfish-library
    PYTYPE_DIR: redfish
    LIBRARY: "http://github.hpe.com/intelligent-provisioning/python-redfish-library.git"
    RESULTS_URL: http://infinitymaster.us.rdlabs.hpecorp.net:1051/Drone_Git_Build_Data/
    DOCS: false
    PYLINT: true
    UNIT_TEST: true
  commands:
  - easy_install distribute
  - echo "python_version = 2.7" >> tests/pytype/pytype.cfg
  - more tests/pytype/pytype.cfg
  - echo "Installing Python iLORest Library"
  - python setup.py sdist --formats=zip
  - pip install --upgrade dist/python-ilorest-library-*.zip
  - echo "Installing Additional Libraries"
  - pip install --upgrade pip
  - pip install pylint pytest pytest-logging mock requests ntplib datetime pytz pytype inspect-it future six
  - python /tmp/store/libs_parse_installer.py
  - echo "Running Analysis" 
  - python /tmp/store/drone_analyzer.py
  - more tmp.json
  - echo "Issuing GitHub Comments"
  - python /tmp/store/github_comment_issuer.py
  #    --cov=./src/extensions/*      
  #    --html=./tests/ilorest_tests/_results/tests/index.html \
  #    --cov-report=html:./test/ilorest_tests/_results/py2/coverage \
  #    --junit-xml=./tests/ilorest_tests/_results/py2/test-results.xml \
  #    --cov-report=html:./tests/ilorest_tests/_results/py2/coverage.xml
  #- cat ./tests/pmemtests/_results/data/pylint-results.txt
  #- cat ./tests/pmemtests/_results/data/pylint-py3-results.txt
  #- echo $rc2
  # fatal=1 | error=2 | usage error=32
  #- exit $(( $rc & 35 ))

- name: RIS-library-pytester-3.5
  image: python:3.5
  pull: true
  volumes:
  - name: drone_store
    path: /tmp/store
  environment:
    HTTP_PROXY: http://web-proxy.houston.hpecorp.net:8080
    PYTHON: 3
    GITHUB_USERNAME:
      from_secret: github_username
    GITHUB_PASSWORD:
      from_secret: github_password
    RESTLAX_FILE_PATH: /tmp/store/Restlax_web.txt
    DRONE_STORE_PATH: /tmp/store/
    PYTYPE_CONFIG: tests/pytype/pytype.cfg
    REPO_OWNER: intelligent-provisioning
    REPO_NAME: python-redfish-library
    PYTYPE_DIR: redfish
    LIBRARY: "http://github.hpe.com/intelligent-provisioning/python-redfish-library.git"
    RESULTS_URL: http://infinitymaster.us.rdlabs.hpecorp.net:1051/Drone_Git_Build_Data/
    DOCS: false
    PYLINT: true
    UNIT_TEST: true
  commands:
  - echo "python_version = 3.5" >> tests/pytype/pytype.cfg
  - more tests/pytype/pytype.cfg
  - echo "Installing Python iLORest Library"
  - python setup.py sdist --formats=zip
  - pip install --upgrade dist/python-ilorest-library-*.zip
  - echo "Installing Additional Libraries"
  - pip install --upgrade pip
  - pip install pylint pytest mock requests ntplib datetime pytz pytype redfish inspect-it six
  - python /tmp/store/libs_parse_installer.py
  - echo "Running Analysis" 
  - python /tmp/store/drone_analyzer.py
  - more tmp.json
  - echo "Issuing GitHub Comments"
  - python /tmp/store/github_comment_issuer.py
  #- pytest tests/unit/ > pytype_results.txt
  #- more pytype_results.txt

#- name: notify-email
# hub.docker.hpecorp.net/ilorest/email_notify:latest
#  image: drillster/drone-email 
#  settings:
#    host: smtp3.hpe.com
#    skip_verify: true
#    port: 25
#    from: grant.oconnor@hpe.com
#    recipients: [grant.oconnor@hpe.com] 
#   #- ILORest-Notify@groups.int.hpe.com

volumes:
- name: drone_store
  host:
    path: /opt/docker_drone_share/
    
trigger:
  event:
  - pull_request